import type { Metadata } from "next";
import localFont from "next/font/local";
import Image from "next/image";
import { AntdRegistry } from '@ant-design/nextjs-registry';

import "./globals.css";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          className="main"
        >
          <Image
              src="/elementBgUp.png"
              alt="background image"
              className="elementBgUp"
              width={212}
              height={213}
          />
          <Image
              src="/elementBgDown.png"
              alt="background image"
              className="elementBgDown"
              width={212}
              height={177}
          />
          <AntdRegistry>
            { children }
          </AntdRegistry>
        </div>
      </body>
    </html>
  );
}
